---
version: 2
builds:
- id: "tucp"
  binary: tucp
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
checksum:
  name_template: 'checksums.txt'
dist: /tmp/tucp/dist
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  github:
    owner: alphauslabs
    name: tucp
brews:
- repository:
    owner: alphauslabs
    name: homebrew-tap
  name: tucp
  homepage: "https://github.com/alphauslabs/tucp"
  description: "The official command line interface for Alphaus TrueUnblended Control Plane service."
  directory: Formula
  install: |
    bin.install "tucp"
  test: |
    assert_match /Command line interface for /, shell_output("#{bin}/tucp -h", 0)
