---
name: main

on:
  push:
    branches: [ main ]
    tags: ['*']
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    if: "!contains(github.event.commits[0].message, 'ci skip')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-go@v4
      with:
        go-version: '1.25'

    - uses: extractions/netrc@v2
      with:
        machine: github.com
        username: mobingideployer
        password: ${{ secrets.GH_PAT }}

    - name: 'Run tests'
      env:
        GOPRIVATE: github.com/alphauslabs
      run: |
        go test -v ./...

    - name: 'Run goreleaser'
      uses: goreleaser/goreleaser-action@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        distribution: goreleaser
        version: latest
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
