---
name: main

on:
  push:
    branches: [ main ]
    tags: ['*']
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    if: "!contains(github.event.commits[0].message, 'ci skip')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: 'Setup Go'
      uses: actions/setup-go@v4
      with:
        go-version: '1.25'

    # - name: 'Build binary'
    #   if: startsWith(github.event.ref, 'refs/heads/')
    #   run: |
    #     make

    - name: 'Run tests'
      run: |
        eval "$(ssh-agent -s)"
        ssh-add - <<< "${{ secrets.DK_BLUE_INTERNAL_GO }}"
        git config --global --add url."ssh://git@github.com/".insteadOf "https://github.com/"
        # go test -v ./...
        go build -v

    - name: 'Run goreleaser'
      uses: goreleaser/goreleaser-action@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        distribution: goreleaser
        version: latest
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
